export const HOME_SIDEBAR_SECTION_TITLES = {
    COMMUNITY_RECENT_POSTS: "COMMUNITY RECENT POSTS",
    TOP_POSTS_THIS_WEEK: "TOP 5 POSTS THIS WEEK",
    RECENTLY_VIEWED: "RECENTLY VIEWED",
  };
  
  export const BUTTON_LABELS = {
    CLEAR: "Clear",
  };
  