export const HOME_SIDEBAR_SECTION_TITLES = {
  COMMUNITY_RECENT_POSTS: "COMMUNITY RECENT POSTS",
  TOP_POSTS_THIS_WEEK: "TOP 5 POSTS THIS WEEK",
  RECENTLY_VIEWED: "RECENTLY VIEWED",
};
  
export const BUTTON_LABELS = {
  CLEAR: "Clear",
};
  
export const COMMUNITY_SIDEBAR_SECTION_TITLES = {
  TOP_POSTS_BY_CATEGORY_THIS_WEEK: "TOP POSTS BY CATEGORY THIS WEEK",
  CATEGORIES: "CATEGORIES",
  NEW_MEMBERS_THIS_WEEK: "NEW MEMBERS THIS WEEK",
  USERS_ONLINE: "USERS ONLINE",
  NO_DATA_AVAILABLE: "NO DATA AVAILABLE",
};

export const PROFILE_SIDEBAR_SECTION_TITLES = {
  TOP_LIKED_POSTS: "TOP LIKED POSTS",
  RECENT_POSTS: "RECENT POSTS",
  JOINED_COMMUNITIES: "JOINED COMMUNITIES",
};
  